{
  "hash": "c5aa767b3435b9e9c0be13952f016e8a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Dungeons! But mostly, Dragons!\"\nauthor: \"Phoebe Jones\"\ndate: \"2026-03-13\"\nimage: \"dragons.avif\"\n---\n\n## Introduction\n\nFor this post, I worked with a data set of 330 monsters from Dungeons and Dragons, accessed from the Tidy Tuesday github repository. <https://github.com/rfordatascience/tidytuesday/blob/main/data/2025/2025-05-27/readme.md>. The data set contains 33 variables; the variables relevant to this post are `name`, `cr`, `size`, `ac`, and `hp_number`. `name` is the monster's name (like Awakened Tree or Purple Worm), `cr` is the monster's challenge rating (how difficult it is to defeat in battle), `size` is the monster's size (in relative categories), `ac` is the monster's armor class (how difficult it is to hit), and `hp_number` is the the amount of health that the monster has.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(ggeffects)\ntheme_set(theme_linedraw())\n\nmonsters <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-05-27/monsters.csv')\nmonsters <- monsters |> mutate(size = factor(size))\n```\n:::\n\n\nIn exploring this data set, I was interested in looking at the relationships between monsters' challenge ratings and their other stats.\n\n## To Begin My Adventure\n\nI wanted to start my exploration simply, by looking at the distribution of challenge rating across the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(monsters, aes(x = cr)) +\n  geom_freqpoly() +\n  labs(x = \"Challenge Rating\", y = \"Count\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\nThe above frequency plot shows what I would expect: that there are more monsters of lower challenge ratings and less of higher. This makes sense, as from an adventure standpoint, there would be more use for easier to fight monsters than for very difficult bosses.\n\nChallenge rating is provided to players within the game handbook, but it would be useful to have the ability to predict challenge rating given a monster's stats, especially if one was interested in creating original monsters. This is where I took my exploration next, towards developing a model to predict challenge rating.\n\nI started with using a monster's size and armor class (and an interaction term between the two) to predict challenge rating. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ncr_mod <- lm(cr ~ size + ac + size:ac, monsters)\ncr_mod |> glance()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.803         0.795  2.63      99.0 5.57e-103    13  -780. 1590. 1647.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\nThe above table shows this model has an adjusted r-squared of 0.795, meaning that the model explains 79.5% of the variation in challenge rating. That's not bad! Let's visualize.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_cr <- ggpredict(cr_mod, terms = c(\"ac\",\n                                       \"size\")) |>\n  as.data.frame(terms_to_colnames = TRUE) |>\n  as_tibble()\n\nggplot(pred_cr, aes(y = predicted, x = ac)) +\n  facet_wrap(~ size) +\n  geom_point(data = monsters, aes(y = cr), alpha = 0.3) +\n  geom_line(color = \"orangered4\", linewidth = 1.2) +\n  scale_color_viridis_d() +\n  labs(x = \"Armor Class\", \n       y = \"Challenge Rating\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThis model looks pretty good! But there is still some variation left unexplained and a lot of variables left in the data set, so let's see if we can do better!\n\n## The Journey Continues\n\nTo expand the model, I decided to add HP in the model and expand the visualization to include it. Each size category will now have three lines each, representing the Q1, median, and Q3 values for HP in the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrhp_mod <- lm(cr ~ size + ac + size:ac + hp_number, monsters)\n\ncrhp_mod |> glance()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squared sigma statistic   p.value    df logLik   AIC   BIC\n      <dbl>         <dbl> <dbl>     <dbl>     <dbl> <dbl>  <dbl> <dbl> <dbl>\n1     0.961         0.959  1.17      555. 2.10e-212    14  -512. 1057. 1117.\n# ℹ 3 more variables: deviance <dbl>, df.residual <int>, nobs <int>\n```\n\n\n:::\n:::\n\n\nThe above table shows that this expanded version of the model has an adjusted r-squared of 0.959, meaning that 95.9% of the variation in challenge rating is explained by this model. Pretty great! So let's visualize.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_crhp <- ggpredict(crhp_mod, terms = c(\"ac\",\n                                       \"hp_number [threenum]\",\n                                       \"size\")) |>\n  as.data.frame(terms_to_colnames = TRUE) |>\n  as_tibble()\n\nggplot(pred_crhp, aes(y = predicted, x = ac)) +\n  facet_wrap(~ size) +\n  geom_point(data = monsters, aes(y = cr), alpha = 0.3) +\n  geom_line(aes(color = hp_number), linewidth = 1.5) +\n  scale_color_viridis_d() +\n  labs(x = \"Armor Class\", \n       y = \"Challenge Rating\",\n       color = \"HP\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nLooks great! Except... hold on... what's happening with the Gargantuan monsters? The data seems to show a clear positive trend, so what's with the negative line slope? Let's look at the monsters closer.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonsters_garg <- monsters |> \n  filter(size == \"Gargantuan\")\n\nmonsters_garg |> select(name, ac, hp_number) |> slice(1:15) |> arrange(hp_number) |> knitr::kable()\n```\n\n::: {.cell-output-display}\n\n\n|name                  | ac| hp_number|\n|:---------------------|--:|---------:|\n|Purple Worm           | 18|       247|\n|Roc                   | 15|       248|\n|Ancient Brass Dragon  | 20|       332|\n|Ancient White Dragon  | 20|       333|\n|Dragon Turtle         | 20|       356|\n|Ancient Black Dragon  | 22|       367|\n|Ancient Copper Dragon | 21|       367|\n|Ancient Green Dragon  | 21|       402|\n|Ancient Bronze Dragon | 22|       444|\n|Ancient Silver Dragon | 22|       468|\n|Ancient Blue Dragon   | 22|       481|\n|Kraken                | 18|       481|\n|Ancient Red Dragon    | 22|       507|\n|Ancient Gold Dragon   | 22|       546|\n|Tarrasque             | 25|       697|\n\n\n:::\n:::\n\n\nIt looks like the problem lies with the HP. The Q1, median, and Q3 values represented by the lines on the model are not values of HP present within the Gargantuan monster category. This explains the problem with the lines. So let's make another plot that represents the gargantuan monster category better.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrgarg_mod <- lm(cr ~ ac + hp_number, monsters_garg)\npred_garg <- ggpredict(crgarg_mod, terms = c(\"ac\",\n                                       \"hp_number [threenum]\")) |>\n  as.data.frame(terms_to_colnames = TRUE) |>\n  as_tibble()\n\nggplot(pred_garg, aes(y = predicted, x = ac)) +\n  geom_point(data = monsters_garg, aes(y = cr), alpha = 0.3) +\n  geom_line(aes(color = hp_number), linewidth = 1.2) +\n  scale_color_viridis_d() +\n  labs(x = \"Armor Class\",\n       y = \"Challenge Rating\",\n       color = \"HP\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n## Conclusion\n\nMy conclusions from this data exploration journey have more to do with data visualization techniques than dungeons and dragons. I have seen now possible ways that visualizations can be skewed in much the same way that general summary statistics can be. However, exploring this data has shown me the measures that most likely contribute to the challenge rating of dungeons and dragons monsters. Specifically, a high armor class and high HP contribute to a higher challenge rating.\n\n## Class Connections\n\nFor this blog post, I made use of visualization techniques to show the linear model I built from my data. By using ggpredict, I was able to draw lines showing the predicted values for challenge rating based on my chosen predictors. I made use of faceting and color differentiation to appropriately show the differing lines of best fit.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}